# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MADICORP Open Source Technologies
email: contact@madi-corp.net
description: > # this means to ignore newlines until "baseurl:"
  MADICORP est une entreprise de préstation de services informatiques.
  Nous mettons à votre service notre savoir faire pour vous aider à réaliser vos projets de dévelopement d'application web,
  mobile ou encore de bureau.
  Notre Expertise open source nous permet de vous offrir le meilleur des technologies informatiques adptées à vos besoins quelque soit votre budget.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: madicorpsenegal
github_username:  madicorp

# Build settings
markdown: kramdown
theme: minima
sass:
    style: compressed
    sass_dir: _sass
assets:
  compress:
    css: true | true
    js: true | true
autowrite: true
features:
  automatic_img_size: false
  liquid: true
  integrity: true
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock
